# -*- coding: utf-8 -*-
"""Taller1MT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MT01g6drBpIc3cBxbAe87Bk0oll4nKWn
"""

cantidad_a = int(input("Ingrese cantidad de datos a registrar en el conjunto A "))
conjunto_a = set()
for i in range(cantidad_a):
  elemento = int(input("Escribe un elemento"))
  conjunto_a.add(elemento)

cantidad_b = int(input("Ingrese cantidad de datos a registrar en el conjunto B "))
conjunto_b = set()

for i in range(cantidad_b):
  elemento = int(input("Escribe un elemento"))
  conjunto_b.add(elemento)

print("seleciona una operacion")
print("1. Union")
print("2. Interseccion")
print("3. Diferencia")
print("4. Diferencia simetrica")
opcion = int(input("Tu opcion es: "))

if opcion == 1:
  conjunto_resultado = conjunto_a | conjunto_b
elif opcion == 2:
  conjunto_resultado = conjunto_a & conjunto_b
elif opcion == 3:
  conjunto_resultado = conjunto_a - conjunto_b
else:
  conjunto_resultado = conjunto_a ^ conjunto_b

print("El conjunto resultante es:", conjunto_resultado)
print("La cardinalidad del conjunto resultante es:", len(conjunto_resultado))